app_hazid/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("read/<int:survey_id>/", views.read_survey, name="read_survey"),
    path("create/", views.create_survey, name="create_survey"),
    path("profile/", views.profile_view, name="profile"),
    path("stats/", views.stats, name="stats"),
    path("winners/", views.winners, name="winners"),
    path("qr/", views.qr, name="qr"),

    path('profile/change_password/', views.custom_password_change, name='password_change'),
]

project_hazid/urls.py
from django.contrib import admin
from django.urls import path, include

from app_hazid import views

urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('sign-up/', views.custom_register, name='register'),
    path('admin/', admin.site.urls),
    path("hazid/", include("app_hazid.urls"))
]

app_hazid/models.py
from django.db import models
from django.utils import timezone

from multiselectfield import MultiSelectField

from app_users.models import CustomUser
from app_hazid.utils import ACTIVITY_OBSERVED, I_OBSERVED, POSSIBLE_CONSEQUENCES, CONDITIONS_RELATED


class Survey(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="surveys")
    created_at = models.DateTimeField(default=timezone.now)

    title = models.CharField(max_length=50)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=35)
    company_observed = models.CharField(max_length=20)
    activity_observed = models.CharField(max_length=27, choices=ACTIVITY_OBSERVED, default=None)
    i_observed = models.CharField(max_length=21, choices=I_OBSERVED, default="None")
    possible_consequences = MultiSelectField(max_length=255, choices=POSSIBLE_CONSEQUENCES)
    conditions_related = MultiSelectField(max_length=500, choices=CONDITIONS_RELATED)
    description = models.CharField(max_length=300)
    swa_applied = models.BooleanField(default=False)
    corrective_measures = models.BooleanField(default=False)
    further_action = models.BooleanField(default=False)
    corrective_action = models.CharField(max_length=150)
    reported = models.BooleanField(default=False)
    if_reported = models.CharField(max_length=100, blank=True)

    class Meta:
        verbose_name = "Hazid"
        verbose_name_plural = "Hazids"
    
    def __str__(self):
        return self.title

app_users/models.py
from django.db import models

from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, password, **extra_fields)
    

class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    
    username = models.CharField(max_length=30, unique=False, blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name = "Custom User"
        verbose_name_plural = "Custom Users"


class AllowedUser(models.Model):
    email = models.EmailField(unique=True)
    

    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name = "Allowed User"
        verbose_name_plural = "Allowed Users"

app_hazid/forms.py
from django import forms

from .models import Survey


class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = [field.name for field in Survey._meta.get_fields() if field.name not in ("created_at", "author")]

app_hazid/views.py
from django.shortcuts import get_object_or_404, redirect, render, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count
from django.views import View
from django.utils.decorators import method_decorator

from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.contrib import messages


from .models import Survey
from .forms import SurveyForm

from app_users.models import AllowedUser
from app_users.forms import LoginUserForm, RegisterUserForm, ChangePasswordForm, AllowedUserForm


def custom_register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data["email"]
            
            # if user exist in allowed list
            if AllowedUser.objects.filter(email = user_email).exists():
                form.save()
                user = form.save()

                if "@admin" in user.email:
                    group = Group.objects.get(name="admin")
                else:
                    group = Group.objects.get(name="default")
                group.user_set.add(user)

                return redirect(reverse("index"))
            else:
                return render(
                    request,
                    "registration/register.html",
                    {
                        "form": form,
                        "error_message": "You are not allowed to register."
                    }
                )
    else:
        form = RegisterUserForm()
    return render(request, "registration/register.html", {"form": form})


def custom_login(request):
    if request.method == "POST":
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("app_hazid:index")
    else:
        form = LoginUserForm()
    return render(request, "registration/login.html", {"form": form})


@login_required(login_url="/login/")
def custom_password_change(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            # messages.success(request, "Password changed successfully")
            return redirect("about_me")
    else:
        form = ChangePasswordForm(request.user)
    return render(request, "registration/password_change/password_change_form.html", {"form": form})


@login_required(login_url="/login")
def index(request):
    surveys = Survey.objects.all()
    context = {
        "surveys": surveys[::-1],
    }
    return render(request, "app_hazid/index.html", context)


@login_required(login_url="/login")
def create_survey(request):
    if request.method == "POST":
        form = SurveyForm(request.POST)
        if form.is_valid():
            survey = form.save(commit=False)
            survey.author = request.user
            survey.save()
            return redirect(reverse("read_survey", args=(survey.id,)))
    else:
        form = SurveyForm()
    return render(request, "app_hazid/create_survey.html", {"form": form})


def read_survey(request, survey_id):
    survey = get_object_or_404(Survey, pk=survey_id)
    context = {
        "survey": survey,
    }
    return render(request, "app_hazid/detail.html", context)


@login_required(login_url="/login/")
def profile_view(request):
    if request.method == "POST":
        form = AllowedUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("profile"))
    else:
        form = AllowedUserForm()

    current_user = request.user
    surveys = Survey.objects.filter(author_id=current_user.id)

    context = {
        "current_user": current_user,
        "current_user_id": current_user.id,
        "surveys": surveys,
        "form": form,
    }

    return render(request, "app_hazid/profile.html", context)


def stats(request):
    team_size = AllowedUser.objects.count()
    card_submitted = Survey.objects.count()
    individuals = Survey.objects.values("author_id").annotate(count=Count("author_id"))
    observed_counts = Survey.objects.values("i_observed").annotate(count=Count("i_observed"))

    target_achieved = round(card_submitted * 100 / team_size)
    individuals_percentage = round(individuals.count() * 100 / team_size)

    context = {
        "observed_counts": observed_counts,
        "card_submitted": card_submitted,
        "individuals": individuals,
        "team_size": team_size,
        "target_achieved": target_achieved,
        "individuals_percentage": individuals_percentage,
    }
    return render(request, "app_hazid/stats.html", context)


def winners(request):
    context = {

    }
    return render(request, "app_hazid/winners.html", context)


def qr(request): 
    context = {

    }
    return render(request, "app_hazid/qr.html", context)

app_hazid/templates/app_hazid/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app_hazid/css/style.css' %}">
    
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
</head>
<body>

 <header class="text-white text-center py-3" style="background-color: rgb(35, 57, 69)">
    <h1>HAZARD ID Card</h1>
  </header>

  <!-- Навигационная панель (navbar) -->
  <nav class="navbar navbar-expand-lg" id="navbar">
    <div class="container">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="" role="button" ><i class="fa fa-bars" aria-hidden="true" style="color :#e6e6ff; font-size: 28px;"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">View cards</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_survey' %}">Create a card</a>
                </li>
                {% if user.groups.all.0.name == 'admin' %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stats' %}">Stats</a>
                </li>
                {% endif %}
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'winners' %}">Winners</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'qr' %}">QR</a>
                </li> -->
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">{{user.groups.all.0.name}} | {{ user.email }}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'register' %}" class="btn btn-outline-primary">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
  </nav>

    <main class="container py-4">
        {% block content %}{% endblock %}
    </main>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script> -->
</body>
</html>

app_hazid/templates/app_hazid/create_survey.html
{% extends "app_hazid/base.html" %}

{% block title %} Create a HAZID Card {% endblock %}


{% block content %}
        <div class="container" id="form-group-create">
            <div class="row">
              <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12">
                <form method="post">
                  {% csrf_token %}
                  {{form.errors}}
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Short name of your card">
                  </div>
                  <div class="form-group">
                    <label for="date">When did it happen?</label>
                    <input type="date" class="form-control" id="date" name="date" placeholder="">
                  </div>
                  <div class="form-group">
                    <label for="time">At what time did this happen?</label>
                    <input type="time" class="form-control" id="time" name="time" >
                  </div>
                  <div class="form-group">
                    <label for="location">Location</label>
                    <input type="text" class="form-control" id="location" name="location" placeholder="Where did it happen?">
                  </div>
                  <div class="form-group">
                    <label for="company">Company Observed</label>
                    <input type="text" class="form-control" id="company_observed" name="company_observed" placeholder="Company Observed">
                  </div>

                  <div class="form-group">
                    <label for="activity_observed">Activity Observed</label>
                    <select class="form-control" id="{{ form.activity_observed.id_for_label }}" name="{{ form.activity_observed.name }}">
                      {% for value, label in form.activity_observed.field.choices %}
                          <option value="{{ value }}" {% if value == form.activity_observed.value %}selected{% endif %}>{{ label }}</option>
                      {% endfor %}
                  </select>
                  </div>
                  <div class="form-group">
                    <label for="i_observed">I Observed</label>
                    <select class="form-control" id="{{ form.i_observed.id_for_label }}" name="{{ form.i_observed.name }}">
                      {% for value, label in form.i_observed.field.choices %}
                          <option value="{{ value }}" {% if value == form.i_observed.value %}selected{% endif %}>{{ label }}</option>
                      {% endfor %}
                  </select>
                  </div>

                  <div class="form-group">
                    <label for="possible_consequences">Possible Consequences</label>
                      {% for value, label in form.possible_consequences.field.choices %}
                      <div class="form-check">
                          <input class="form-check-input" type="checkbox" value="{{ value }}" id="{{ value }}" name="{{ form.possible_consequences.name }}"{% if value in form.possible_consequences.value %} checked{% endif %}>
                          <label class="form-check-label" for="{{ value }}">{{ label }}</label>
                      </div>
                      {% endfor %}
                  </div>
                  
                  <div class="form-group conditions_related">
                    <label for="conditions_related">
                      <a href="#conditionsCollapse" data-toggle="collapse">Conditions/Act related to</a>
                    </label>
                    <div class="collapse" id="conditionsCollapse">
                        {% for value, label in form.conditions_related.field.choices %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ value }}" id="{{ value }}" name="{{ form.conditions_related.name }}"{% if value in form.conditions_related.value %} checked{% endif %}>
                            <label class="form-check-label" for="{{ value }}">{{ label }}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                
                  <!-- <div class="form-group">
                    <label for="conditions_related">Conditions/Act related to</label>
                      {% for value, label in form.conditions_related.field.choices %}
                      <div class="form-check">
                          <input class="form-check-input" type="checkbox" value="{{ value }}" id="{{ value }}" name="{{ form.conditions_related.name }}"{% if value in form.conditions_related.value %} checked{% endif %}>
                          <label class="form-check-label" for="{{ value }}">{{ label }}</label>
                      </div>
                      {% endfor %}
                  </div> -->

                  <div class="form-group description">
                    <label for="description" id="description">Describe your observation:</label>
                    <textarea class="form-control no-resize" id="description" name="description" rows="4" placeholder="(maximum 300 characters)"></textarea>
                  </div>
                  
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="swa_applied" id="swa_applied">
                    <label class="form-check-label" for="swa_applied">Has SWA been applied?</label>
                  </div>

                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="corrective_measures" id="corrective_measures">
                    <label class="form-check-label" for="corrective_measures">Have the corrective measures been taken?</label>
                  </div>

                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="further_action" id="further_action">
                    <label class="form-check-label" for="further_action">Further action required?</label>
                  </div>

                  <div class="form-group">
                    <label for="corrective_action">Corrective actions taken/recommended:</label>
                    <textarea class="form-control no-resize" id="corrective_action" name="corrective_action" rows="3"  placeholder="(maximum 150 characters)"></textarea>
                  </div>
                  
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="reported" id="reported">
                    <label class="form-check-label" for="reported">Did you report this to a foreman/supervisor or HES representative?</label>
                  </div>

                  <div class="form-group">
                    <label for="if_reported">If yes, who and when</label>
                    <input type="text" class="form-control" id="if_reported" name="if_reported" placeholder="(maximum 100 characters)">
                  </div>
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit Card</button>
                  </div>
                </form>

              </div>
            </div>
          </div>
{% endblock %}

app_hazid/templates/app_hazid/detail.html
{% extends "app_hazid/base.html" %}

{% block title %}Card details{% endblock %}


{% block content %}
<div class="container" id="detail">

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Title</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.title}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Date</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.date}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Time</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.time}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Location</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.location}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Company observed</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.company_observed}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Activity observed</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.activity_observed}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>I observed</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.i_observed}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Possible consequences</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.possible_consequences}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Conditions/Act related to</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.conditions_related}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Description</h5>
        </div>
        <div class="col-md-8 col-12"  id="description">
            <p >{{survey.description}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Has SWA been applied?</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.swa_applied}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Have the corrective measures been taken?</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.corrective_measures}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Further action required?</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.further_action}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Corrective actions taken/recommended:</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.corrective_action}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>Did you report?</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.reported}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-12">
            <h5>If yes, who and when</h5>
        </div>
        <div class="col-md-8 col-12">
            <p >{{survey.if_reported}}</p>
        </div>
    </div>
</div>
{% endblock %}

app_hazid/templates/app_hazid/index.html
{% extends "app_hazid/base.html" %}

{% block title %} Hazids {% endblock %}


{% block content %}
    <div>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            </ul>
        </nav>
    </div>
    {% for survey in surveys %}
        <div class="card mb-3">

            <div class="card-header">Author:
                <strong>
                    {{ survey.author.email }}
                </strong>
            </div>

            <div class="card-body d-flex flex-row justify-content-between">
                <div>
                    <h5 class="card-title">
                        <a href="{% url 'read_survey' survey.id %}">{{ survey.title }}</a>
                    </h5>
                </div>
            </div>

            <div class="card-footer text-muted">
                Created at: {{survey.created_at}}
            </div>
        </div>

    {% empty %}
        <h4>No cards</h4>
    {% endfor %}

{% endblock %}

app_hazid/templates/app_hazid/profile.html
{% extends "app_hazid/base.html" %}

{% block title %}Profile{% endblock %}


{% block content %}

    <!-- {{ current_user_id }}
    {% if surveys %}
        {{ surveys }}
        {% else %}
        Nothing
    {% endif %} -->

    {% if perms.app_users.add_alloweduser %}
        <form method="post">
            {% csrf_token %}
            <div id="form-group-add-allowed-user">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input name="email" type="email" class="form-control custom-email-input" id="email">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary mb-2">Add</button>
                </div>
            </div>
        </form>
    {% else %}
        <h3>no perms</h3>
    {% endif %}

    <a href="{% url 'password_change' %}">Password change</a>
{% endblock %}

app_hazid/templates/app_hazid/qr.html
{% extends "app_hazid/base.html" %}

{% block title %}QR{% endblock %}


{% block content %}

{% endblock %}

app_hazid/templates/app_hazid/stats.html
{% extends "app_hazid/base.html" %}

{% block title %}Stats{% endblock %}


{% block content %}
    {% if observed_counts %}
        {% for i in observed_counts %}
            <li>{{ i.i_observed }} - {{ i.count }}</li>
        {% endfor %}
    {% else %}
        <h4>No Stats</h4>
    {% endif %}

    <li>Team size - {{ team_size }}</li>
    <li>Card Submitted - {{ card_submitted }}</li>
    <li style="color: red;">Target Achieved - {{ target_achieved }}%</li>
    <li>No. of Individuals who Participated - {{ individuals.count }}</li>
    <li style="color: red;">Individuals Participating - {{ individuals_percentage }}%</li>

{% endblock %}

app_hazid/templates/app_hazid/winners.html
{% extends "app_hazid/base.html" %}

{% block title %}Winners{% endblock %}


{% block content %}

{% endblock %}